# Generated by Django 6.0.3 on 2026-03-13 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CH', 'Chess.com'), ('LI', 'Lichess')], db_index=True, max_length=2)),
                ('game_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('game_url', models.URLField(blank=True, max_length=500)),
                ('date_played', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('utc_date', models.DateField(blank=True, null=True)),
                ('utc_time', models.TimeField(blank=True, null=True)),
                ('time_class', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('correspondence', 'Correspondence')], db_index=True, max_length=20)),
                ('time_control', models.CharField(blank=True, max_length=20)),
                ('white_player', models.CharField(db_index=True, max_length=100)),
                ('black_player', models.CharField(db_index=True, max_length=100)),
                ('my_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], db_index=True, max_length=1)),
                ('termination', models.CharField(blank=True, max_length=50)),
                ('win_method', models.CharField(blank=True, choices=[('RES', 'Resignation'), ('CHM', 'Checkmate'), ('TIM', 'Timeout'), ('ABD', 'Abandoned'), ('AGR', 'Agreed Draw'), ('STM', 'Stalemate'), ('REP', 'Repetition'), ('INS', 'Insufficient Material'), ('TVI', 'Time vs Insufficient'), ('OTH', 'Other')], max_length=3, null=True)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('my_rating', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3500)])),
                ('opponent_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3500)])),
                ('opponent_name', models.CharField(blank=True, max_length=100)),
                ('opponent_url', models.URLField(blank=True, max_length=500)),
                ('rating_change', models.IntegerField(blank=True, null=True)),
                ('eco', models.CharField(blank=True, max_length=3)),
                ('opening', models.CharField(blank=True, db_index=True, max_length=200)),
                ('opening_url', models.URLField(blank=True, max_length=500)),
                ('fen', models.CharField(blank=True, max_length=100)),
                ('pgn', models.TextField(blank=True)),
                ('moves', models.TextField(blank=True)),
                ('move_count', models.IntegerField(default=0)),
                ('my_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('opponent_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('moves_with_eval', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_played', '-start_time'],
                'indexes': [models.Index(fields=['platform', 'date_played'], name='WebChessSta_platfor_7f5612_idx'), models.Index(fields=['result', 'my_color'], name='WebChessSta_result_6d4a5c_idx'), models.Index(fields=['opening'], name='WebChessSta_opening_ac0fc1_idx'), models.Index(fields=['time_class'], name='WebChessSta_time_cl_8d6f8d_idx'), models.Index(fields=['my_rating'], name='WebChessSta_my_rati_a3fbb3_idx'), models.Index(fields=['opponent_name'], name='WebChessSta_opponen_0e6f0f_idx'), models.Index(fields=['created_at'], name='WebChessSta_created_0af36a_idx')],
            },
        ),
    ]
