# Generated by Django 6.0.3 on 2026-03-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChessStats', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_active'], name='WebChessSta_is_acti_b4a347_idx'),
        ),
    ]
