# Generated by Django 4.2.29 on 2026-03-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChessStats', '0002_game_webchesssta_is_acti_b4a347_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='move_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
